# This env file was creating using...
# (1) anaconda docs
#	https://docs.conda.io/projects/conda/en/latest/user-guide/tasks/manage-environments.html
# (2) grayskull to list deps
#	https://www.marcelotrevisani.com/grayskull
#
# To install this env, use `conda env create -f environment.yaml`
name: simmate_dev
channels:
    - conda-forge
dependencies:
    - black >=22.1.0
    - click >=8.0.3
    - coverage >=6.2
    - dask-core >=2021.12.0
    - dask-jobqueue >=0.7.3
    - dj-database-url >=0.5.0
    - django >=4.0.0
    - django-allauth >=0.50.0
    - django-crispy-forms >=1.13.0
    - django-pandas >=0.6.6
    - django-filter >=21.1
    - djangorestframework >=3.13.1
    - matminer >=0.7.6
    - numpy >=1.22.0
    - pandas >=1.3.5
    - pdoc >=11.0.0
    - plotly >=5.4.0
    # - prefect >=2.0  # NOT AVAILABLE ON CONDA UNTIL STABLE RELEASE
    - pip:
        - prefect==2.0b7
    - pymatgen >=2022.1.9
    - pymatgen-analysis-diffusion >=2021.4.29
    - pytest >=6.2.5,<7.1
    - pytest-django >=4.5.2
    - python >=3.10
    - pytest-mock >=3.7.0
    - pytest-xdist >=2.5.0
    - pyyaml >=6.0
    - tqdm >=4.62.3
    # Recommended IDE for development -- We leave this as a separate install
    # because it's up to you and Spyder is a large package with many dependencies.
    # - spyder >=5.1.5
